Update tools dir to use Maven 3.2.1

diff --git a/tools/maven/bin/mvnyjp b/tools/maven/bin/mvnyjp
--- a/tools/maven/bin/mvnyjp
+++ b/tools/maven/bin/mvnyjp
@@ -169,8 +169,8 @@ if [ -z "$JAVACMD" ] ; then
 fi
 
 if [ ! -x "$JAVACMD" ] ; then
-  echo "Error: JAVA_HOME is not defined correctly."
-  echo "  We cannot execute $JAVACMD"
+  echo "Error: JAVA_HOME is not defined correctly." >&2
+  echo "  We cannot execute $JAVACMD" >&2
   exit 1
 fi
 
@@ -191,7 +191,7 @@ if $cygwin; then
 fi
 
 if [ ! -f "$YJPLIB" ]; then
-  echo "Unable to autodetect the YJP library location. Please set YJPLIB variable"
+  echo "Error: Unable to autodetect the YJP library location. Please set YJPLIB variable" >&2
   exit 1
 fi
 
