[JBAS-8790] Update bundled Maven from 3.0-beta-1 to 3.0.2, and remove unecessary maven ant tasks

diff --git a/tools/maven/bin/mvnyjp b/tools/maven/bin/mvnyjp
--- a/tools/maven/bin/mvnyjp
+++ b/tools/maven/bin/mvnyjp
@@ -31,11 +31,8 @@
 #   MAVEN_OPTS - parameters passed to the Java VM when running Maven
 #     e.g. to debug Maven itself, use
 #       set MAVEN_OPTS=-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000
+#   MAVEN_SKIP_RC - flag to disable loading of mavenrc files
 # ----------------------------------------------------------------------------
-
-YJPLIB=/applications/YourKit.app/bin/mac/libyjpagent.jnilib
-
-MAVEN_OPTS=-agentpath:$YJPLIB=onexit=snapshot,onexit=memory,tracing,onlylocal
 
 QUOTED_ARGS=""
 while [ "$1" != "" ] ; do
@@ -45,12 +42,16 @@ while [ "$1" != "" ] ; do
 
 done
 
-if [ -f /etc/mavenrc ] ; then
-  . /etc/mavenrc
-fi
+if [ -z "$MAVEN_SKIP_RC" ] ; then
 
-if [ -f "$HOME/.mavenrc" ] ; then
-  . "$HOME/.mavenrc"
+  if [ -f /etc/mavenrc ] ; then
+    . /etc/mavenrc
+  fi
+
+  if [ -f "$HOME/.mavenrc" ] ; then
+    . "$HOME/.mavenrc"
+  fi
+
 fi
 
 # OS specific support.  $var _must_ be set to either true or false.
@@ -69,6 +70,10 @@ case "`uname`" in
            if [ -z "$JAVA_HOME" ] ; then
              JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
            fi
+           if [ -z "$YJP_HOME" ]; then
+             YJP_HOME=/Applications/YourKit.app
+           fi
+           YJPLIB=$YJP_HOME/bin/mac/libyjpagent.jnilib
            ;;
 esac
 
@@ -157,6 +162,13 @@ if $cygwin; then
   [ -n "$HOME" ] &&
     HOME=`cygpath --path --windows "$HOME"`
 fi
+
+if [ ! -f "$YJPLIB" ]; then
+  echo "Unable to autodetect the YJP library location. Please set YJPLIB variable"
+  exit 1
+fi
+
+MAVEN_OPTS="-agentpath:$YJPLIB=onexit=snapshot,onexit=memory,tracing,onlylocal $MAVEN_OPTS"
 
 exec "$JAVACMD" \
   $MAVEN_OPTS \
